bot_version = '<b>v.4.2</b>\n\n<code>MACBETH CRYPTO BOT</code>'
# https://t.me/macbeth_crypto_bot


telegram_token = '5812953435:AAGv2qPkrpbAHnefWn-eSfbBJ1xKN-rehmw'
# 6282420047:AAHnHweWAo4t0adcOKkPFaM7S-SKJe5NiDA
binance_token = 'Wi5Pl9cUXGSqhYiieGrmyc6kAt4gh8SYYRvEOXNdnNpipYwDnTG5B0AZXUJR70yi'
binance_secret = 'JKHfBqlbFs6RH6Hd06CjBnwEfCyeYpXLElDlMYewd0GQg0PU9LUUTWlCIdQPAprg'
bybit_token = 'gPTNlbNqvHjI0r2qZP'
bybit_secret = 'e4AUc50RRCi41KTYh7eQwUmeUw9Vc1Gj9UGY'


owner = 892023960
logs_chat_id = -1001843152000
notifications_chat_id = -1001254715451


time_for_spam_ban = 1 # seconds
time_for_check_start = 15


time_frades = ['u1m', 'u5m', 'u15m', 'u30m']
time_frades_minutes = [1, 5, 15, 30]
time_frades_precents = [0.6, 1.8, 2.55, 3.1]


access_denied = "<b>У вас недостаточно прав для выполнения данной команды!\nYou don't have enough rights to execute this command!</b>"


cmd_coins = ['BTCBUSD', 'ETHBUSD', 'BNBBUSD', 'XRPBUSD', 'ADABUSD', 'DOGEBUSD', 'MATICBUSD', 'SOLBUSD', 'DOTBUSD',
'AVAXBUSD', 'APTBUSD', 'ARBUSDT', 'ATOMBUSD', 'NEARBUSD', 'UNIBUSD', 'LDOBUSD', 'HBARBUSD', 'APEBUSD',
'OPBUSD', 'AAVEBUSD', 'WAVESBUSD', 'LTCBUSD']

binance_coins = ['BTCBUSD', 'APTBUSD', 'XRPBUSD', 'SOLBUSD', 'ZILBUSD', 'RSRBUSD', 'TRBBUSD', 'CRVBUSD', 'SXPBUSD',
'UNIBUSD', 'BNBBUSD', 'ETHBUSD', 'RVNBUSD', 'XLMBUSD', 'ADABUSD', 'LTCBUSD', 'CHZBUSD', 'FTMBUSD', 'ONEBUSD', 'DOTBUSD',
'ZECBUSD', 'GMTBUSD', 'ATOMBUSD', 'KAVABUSD', 'FLOWBUSD', 'CELOBUSD', 'DOGEBUSD', 'MASKBUSD', 'DASHBUSD', 'BANDBUSD',
'ALGOBUSD', 'MATICBUSD', 'WAVESBUSD', 'SUSHIBUSD', 'IOTABUSD', 'JASMYBUSD', 'LEVERBUSD', 'GRTBUSD', 'INJBUSD', 'IMXBUSD',
'MAGICBUSD', 'RNDRBUSD', 'CHRBUSD', 'ARPABUSD', 'UNFIBUSD', 'EOSBUSD', 'HBARBUSD', 'REEFBUSD', 'LINKBUSD', 'ETCBUSD',
'TRXBUSD', 'BCHBUSD', 'QTUMBUSD', 'VETBUSD', 'EURBUSD', 'ICXBUSD', 'BTSBUSD', 'BNTBUSD', 'NEOBUSD', 'XTZBUSD', 'BATBUSD',
'ENJBUSD', 'NANOBUSD', 'ONTBUSD', 'STRATBUSD', 'AIONBUSD', 'BTTBUSD', 'TOMOBUSD', 'XMRBUSD', 'DATABUSD', 'CTSIBUSD', 'ERDBUSD',
'WRXBUSD', 'KNCBUSD', 'LRCBUSD', 'GBPBUSD', 'DGBBUSD', 'COMPBUSD', 'BKRWBUSD', 'SNXBUSD', 'VTHOBUSD', 'DCRBUSD', 'STORJBUSD',
'IRISBUSD', 'MKRBUSD', 'RUNEBUSD', 'MANABUSD', 'LENDBUSD', 'ZRXBUSD', 'AUDBUSD', 'FIOBUSD', 'AVABUSD', 'BALBUSD', 'YFIBUSD',
'BLZBUSD', 'KMDBUSD', 'JSTBUSD', 'SRMBUSD', 'ANTBUSD', 'SANDBUSD', 'OCEANBUSD', 'NMRBUSD', 'LUNABUSD', 'IDEXBUSD', 'PAXGBUSD',
'WNXMBUSD', 'BZRXBUSD', 'YFIIBUSD', 'KSMBUSD', 'EGLDBUSD', 'DIABUSD', 'BELBUSD', 'SWRVBUSD', 'WINGBUSD', 'CREAMBUSD', 'AVAXBUSD',
'FLMBUSD', 'CAKEBUSD', 'XVSBUSD', 'ALPHABUSD', 'VIDTBUSD', 'AAVEBUSD', 'NEARBUSD', 'FILBUSD', 'AERGOBUSD', 'AUDIOBUSD', 'CTKBUSD',
'BOTBUSD', 'KP3RBUSD', 'AXSBUSD', 'HARDBUSD', 'DNTBUSD', 'CVPBUSD', 'ROSEBUSD', 'SYSBUSD', 'HEGICBUSD', 'PROMBUSD', 'SKLBUSD',
'COVERBUSD', 'GHSTBUSD', 'BTCSTBUSD', 'TRUBUSD', 'PAXBUSD', 'CKBBUSD', 'TWTBUSD', 'LITBUSD', 'SFPBUSD', 'FXSBUSD', 'DODOBUSD',
'BAKEBUSD', 'UFTBUSD', '1INCHBUSD', 'IOSTBUSD', 'OMGBUSD', 'ACMBUSD', 'LINABUSD', 'PERPBUSD', 'SUPERBUSD', 'CFXBUSD', 'XVGBUSD',
'EPSBUSD', 'AUTOBUSD', 'ARBUSDT', 'LDOBUSD', 'APEBUSD', 'OPBUSD']

bybit_coins = ['RNDRUSDT', 'NEARUSDT', 'STXUSDT', 'AVAXUSDT', 'LDOUSDT', 'SXPUSDT', 'AGLDUSDT', 'ATOMUSDT',
'OMGUSDT', 'LINKUSDT', 'FILUSDT', 'GMTUSDT', 'ACHUSDT', 'LINAUSDT', 'RENUSDT', 'DOTUSDT', 'BLURUSDT',
'SHIB1000USDT', 'DYDXUSDT', 'SANDUSDT', 'FLRUSDT', 'GALUSDT', 'CHZUSDT', 'COCOSUSDT', 'ICXUSDT', 'AXSUSDT',
'EOSUSDT', 'GRTUSDT', 'YFIUSDT', 'AGIXUSDT', 'ICPUSDT', 'FETUSDT', 'LUNA2USDT', 'IMXUSDT', 'AUDIOUSDT',
'MAGICUSDT', 'NKNUSDT', 'JOEUSDT', 'REQUSDT', 'GPTUSDT', 'STGUSDT', '1000BONKUSDT', 'ASTRUSDT', 'LQTYUSDT',
'ZRXUSDT', 'ENJUSDT', 'KAVAUSDT', 'CRVUSDT', 'ANTUSDT', 'BCHUSDT', 'ALGOUSDT', 'AAVEUSDT', 'HOOKUSDT', 'MANAUSDT',
'SNXUSDT', 'MINAUSDT', 'ARPAUSDT', 'RUNEUSDT', 'BELUSDT', 'WAVESUSDT', 'NEOUSDT', 'JASMYUSDT', 'HBARUSDT',
'FXSUSDT', 'GMXUSDT', 'WOOUSDT', 'OCEANUSDT', 'ONTUSDT', 'SUSHIUSDT', 'UNIUSDT', 'ANKRUSDT', 'ARUSDT', 'XLMUSDT',
'THETAUSDT', 'KSMUSDT', 'ZECUSDT', 'RPLUSDT', 'LPTUSDT', '1000LUNCUSDT', 'HFTUSDT', 'ONEUSDT', '1INCHUSDT',
'1000FLOKIUSDT', 'BANDUSDT', 'SSVUSDT', 'ROSEUSDT', 'ALICEUSDT', 'UNFIUSDT', 'FLOWUSDT', 'CELOUSDT', 'LRCUSDT',
'KNCUSDT', 'XMRUSDT', 'ZILUSDT', 'MKRUSDT', 'HIGHUSDT', 'DENTUSDT', 'TWTUSDT', 'C98USDT', 'VETUSDT', 'TRBUSDT',
'COREUSDT', 'GFTUSDT', 'RSRUSDT', 'COTIUSDT', 'ENSUSDT', 'BICOUSDT', 'DODOUSDT', 'BLZUSDT', 'ZENUSDT', 'STORJUSDT',
'ILVUSDT', 'LOOKSUSDT', 'PEOPLEUSDT', 'SLPUSDT', 'IOSTUSDT', 'EGLDUSDT', 'CKBUSDT', 'COMPUSDT', 'TOMOUSDT', 'SFPUSDT',
'DASHUSDT', 'FLMUSDT', 'BATUSDT', 'API3USDT', 'ALPHAUSDT', 'RLCUSDT', 'CREAMUSDT']
